### ISSUE TITLE
Ability to sign unsigned transactions

### ISSUE THREAD

**Issue by junhaoyap** [micovi/zilcli#24]
We have a signing procedure where we need to be able to do the following:

1. Generate unsigned transaction to the multisig wallet (can be from an online machine through ZIL GoSDK or similar)
2. Move the unsigned transaction to an offline machine and sign it (this machine may not connect to the internet at all which is where this tool comes in handy as it can be installed via a .pkg file)
3. Move the now signed transaction back to the online machine where we generated the unsigned transaction and broadcast it to Zilliqa blockchain

When we looked through the tool we couldn't find the ability to do that, could we have that feature please?

**Comment by micovi** [comment]
Hello, I posted a release (2.0.2) with a new command `tx:sign` that can be used to sign any transactions.

Here is some documentation:
https://zilcli.app/#/?id=how-to-sign-a-transaction-201

PS: There is also a ledger:sign that is currently not working correctly.

**Comment by junhaoyap** [comment]
Hey @micovi thank you for the quick turnaround, got confirmation on Discord that `ledger:sign` is now working correctly, can I confirm that that is correct and which version would that be?

**Comment by micovi** [comment]
Hi, this issue can be closed. v2.0.5 got tx:sign and ledger:sign commands fixed and confirmed to work.
