### ISSUE TITLE
Process batch transfers

### ISSUE THREAD

**Issue by reb0rn21** [micovi/zilcli#4]
I tried to push with <<EOF private key to zil-cli but it did not work, any way to make it process batch transactions from list of addresses and balance that need to be sent?

**Comment by micovi** [comment]
Hi, we are currently working on a feature that enables processing batch transactions from groups. I will update this issue as soon as we implement it.

**Comment by micovi** [comment]
We introduced a batch transfer command https://github.com/micovi/zilcli#zilcli-txbatch currently available on dev mode. 

We will introduce it into binaries when we release the zilcli v2.0 version :)
