### ISSUE TITLE
Convert to Bech32 checksum format

### ISSUE THREAD

**Issue by snowsledge** [micovi/zilcli#9]
**Is your feature request related to a problem? Please describe.**

Due to EIP-55 being not widely adopted by wallets and exchanges, the 20-bytes `base16` checksum variation used by Zilliqa protocol to prevent the loss of funds sent to an Ethereum address is a not viable solution.

**Describe the solution you'd like**
Zilliqa shall adopt a variation of the `bech32` checksum format on the wallets/SDKs level in order to prevent Users from sending ERC20 ZIL tokens from their Ethereum wallets (i.e. MyCrypto/MyEtherWallet) to an native ZIL address and vice versa.

Please note that the native protocol will still utilise the 20-bytes `base16` checksum on the backend. This is a cosmetic change of the 20-bytes `base16` checksum address to `bech32` checksum format that is enforced on the wallets/SDKs level only. It will only be visible to end-users.

**Describe alternatives you've considered**
N/A

**Additional context**
Please refer to the technical specification on this new address standard:
https://github.com/Zilliqa/Zilliqa/wiki/Address-Standard

zilliqa-js `v0.6.1` includes the `Bech32` utility methods that can be imported for zilcli:
https://github.com/Zilliqa/Zilliqa-JavaScript-Library/blob/dev/packages/zilliqa-js-crypto/src/bech32.ts

**Comment by micovi** [comment]
The new zilcli version uses bech32 format addresses. I will close the issue when I will release the binary compiled version of the new zilcli
